### ISSUE TITLE
Remove bottom layer soldermask on PCB edge for proper grounding to case

### ISSUE THREAD

**Issue by wm93** [bvernoux/EMC_5uH_LISN#4]
Read through the [EEVblog thread regarding the LISN](https://www.eevblog.com/forum/projects/5uh-lisn-for-spectrum-analyzer-emcemi-work/102/) and noticed, that the current layout is missing the soldermask keepout on PCB edge for a proper grounding to the Hammond 1590B case.

Was this intentional or does it require a fix?

**Comment by bvernoux** [comment]
Yes it is a mistake because the keepout area was not done correctly and I have removed it and it requires to add a mask for better grounding of the case with the PCB on Bottom layer border

**Comment by bvernoux** [comment]
@wm93 tell me if you see something to improve else we can close this issue
